DROP DATABASE LIBRARY;
CREATE DATABASE LIBRARY;

USE LIBRARY;

CREATE TABLE BOOKS(
    BOOK_ID INT NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(200) NOT NULL,
    AUTHOR VARCHAR(200),
    GENRE VARCHAR(200), 
    YEAR_PUBLISHED INT,
    PRIMARY KEY(BOOK_ID)
    AVAILABILITY ENUM('AVAILABLE', 'BORROWED') DEFAULT 'AVAILABLE';
);

CREATE TABLE MEMBERS(
    MEMBER_ID INT NOT NULL AUTO_INCREMENT,
    MEMBER_NAME VARCHAR(200) NOT NULL,
    EMAIL VARCHAR(200),
    PHONE VARCHAR(15),
    PRIMARY KEY(MEMBER_ID)
);

CREATE TABLE BORROWING_RECORDS(
    RECORD_ID INT NOT NULL AUTO_INCREMENT,
    MEMBER_ID INT NOT NULL,
    BOOK_ID INT NOT NULL,
    BORROW_DATE DATE,
    RETURN_DATE DATE,
    FOREIGN KEY(MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID),
    FOREIGN KEY(BOOK_ID) REFERENCES BOOKS(BOOK_ID),
    PRIMARY KEY(RECORD_ID)
);



INSERT INTO BOOKS(TITLE, AUTHOR, GENRE, YEAR_PUBLISHED) VALUES(
    'Harry Potter',
    'JK Rowling',
    'Fantasy',
    1997
),(
    'Atomic Habits',
    'James Clear',
    'Self Help',
    2018
),(
    'Ponniyin Selvan',
    'Kalki Krishnamoorthy',
    'Historical Fantasy',
    1954
);


INSERT INTO MEMBERS(MEMBER_NAME,EMAIL,PHONE) VALUES(
    'John',
    'john67@gmail.com',
    45464546
),(
    'Hari',
    'hari56@gmail.com',
    83926537
),(
    'Shyam',
    'shyam90@gmail.com',
    120934875
);


INSERT INTO BORROWING_RECORDS(MEMBER_ID,BOOK_ID,BORROW_DATE,RETURN_DATE) VALUES(
    2,
    1,
    '2024/06/06',
    '2024/07/22'
),(
    1,
    3,
    '2024/03/11',
    '2024/05/02'
),(
    3,
    2,
    '2024/03/15',
    '2024/03/29'
);


SELECT * FROM books;
SELECT * FROM members;
SELECT * FROM borrowing_records;
